#!/bin/bash

# Fail on unset variables and errors
set -euo pipefail

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $SCRIPTDIR/helper.sh

export SSH_KEY_FILE=""
export PULL_SECRET_FILE=""
export RELEASE_IMAGE_VERSION=""
export RELEASE_IMAGE_URL=""
export ARCH=""
export DIR_PATH=""

# Check user provided params
[[ $# -lt 2 ]] && usage
parse_inputs "$@"
validate_inputs
setup_vars

source $SCRIPTDIR/logging.sh

function create_appliance_config() {
    appliance_work_dir="${DIR_PATH}/$full_ocp_version/appliance"
    mkdir -p "${appliance_work_dir}"
    if [ ! -f "${appliance_work_dir}"/appliance-config.yaml ]; then
        # echo "Creating appliance config appliance-config.yaml in directory ${appliance_work_dir}"
        # cfg=${appliance_work_dir}/appliance-config.yaml
        echo "Creating appliance config appliance-config.yaml in directory /"
        cfg=/appliance-config.yaml
        cat << EOF >> ${cfg}  
apiVersion: v1beta1
kind: ApplianceConfig
diskSizeGB: 200
pullSecret: '$(cat "${PULL_SECRET_FILE}")'
stopLocalRegistry: false
enableDefaultSources: false # Enables all default CatalogSources (on openshift-marketplace namespace). Should be disabled for disconnected environments.
useDefaultSourceNames: true # Renames CatalogSource names generated by oc-mirror to the default naming. E.g. 'redhat-operators' instead of 'cs-redhat-operator-index-v4-19'.
enableInteractiveFlow: true
EOF

        if [[ -n "$SSH_KEY_FILE" ]]; then
            cat << EOF >> ${cfg} 
sshKey: '$(cat "${SSH_KEY_FILE}")'
EOF
        fi

        cat << EOF >> ${cfg} 
additionalImages:
  - name: registry.redhat.io/rhel9/support-tools:latest
operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.20
    packages:
      - name: kubevirt-hyperconverged
        channels:
          - name: stable
      - name: mtv-operator
        channels:
          - name: release-v2.8
      - name: kubernetes-nmstate-operator
        channels:
          - name: stable
      - name: node-healthcheck-operator
        channels:
          - name: stable          
      - name: node-maintenance-operator
        channels:
          - name: stable
      - name: fence-agents-remediation
        channels:
          - name: stable          
      - name: cluster-kube-descheduler-operator
        channels:
          - name: stable
EOF

        if [ -n "${RELEASE_IMAGE_VERSION}" ]; then
            cat << EOF >> ${cfg}
ocpRelease:
  version: $major_minor_patch_version
  channel: candidate
  cpuArchitecture: $ARCH
EOF
        fi
        if [ -n "${RELEASE_IMAGE_URL}" ]; then
            cat << EOF >> ${cfg}
ocpRelease:
  version: $major_minor_patch_version
  url: $RELEASE_IMAGE_URL
EOF
        fi
    else
        echo "Skip creating appliance config. Reusing ${appliance_work_dir}/appliance-config.yaml"
    fi
}

function create_operator_crs() {
    openshift_dir="${appliance_work_dir}/openshift"
    crs_dir="${openshift_dir}/crs"
    mkdir -p ${crs_dir}

    cnv_cr=${crs_dir}/cnv_cr.yaml
    cat << EOF >> ${cnv_cr}
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: "openshift-cnv"
EOF

    descheduler_cr=${crs_dir}/kubedescheduler_cr.yaml
    cat << EOF >> ${descheduler_cr}
apiVersion: operator.openshift.io/v1
kind: KubeDescheduler
metadata:
  name: cluster
  namespace: openshift-kube-descheduler-operator
spec:
  managementState: Managed
  deschedulingIntervalSeconds: 30
  mode: Automatic
  profiles:
    - DevKubeVirtRelieveAndMigrate
  profileCustomizations:
    devEnableSoftTainter: true
    devDeviationThresholds: AsymmetricLow
    devActualUtilizationProfile: PrometheusCPUCombined
EOF

    machineconfig_worker_psi=${openshift_dir}/99-openshift-machineconfig-worker-psi-karg.yaml
    cat << EOF >> ${machineconfig_worker_psi}
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-openshift-machineconfig-worker-psi-karg
spec:
  kernelArguments:
    - psi=1
EOF
}

create_appliance_config
create_operator_crs
