FROM quay.io/centos/centos:stream8

RUN dnf install -y "dnf-command(config-manager)" && \
	dnf config-manager --set-enabled powertools && \
	dnf install -y \
		git \
		golang \
		nmstate-devel && \
	dnf clean all
