# For CI jobs like gofmt and govet
FROM quay.io/centos/centos:stream8

RUN dnf install -y "dnf-command(config-manager)" && \
	dnf config-manager --set-enabled powertools && \
	dnf install -y \
		iputils \
		git \
		golang \
		nmstate-devel && \
	dnf clean all

COPY --from=src /go/src /go/src
WORKDIR /go/src/github.com/openshift/agent-installer-utils/
ENV GOCACHE=/tmp

RUN chmod -R u+rwX,go+rX /agent-installer-utils
