FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.20-openshift-4.14 AS builder
    WORKDIR /go/src/github.com/openshift/agent-installer-utils
    COPY . .
    RUN dnf install -y gcc nmstate-devel nmstate-libs && dnf clean all
    RUN ./hack/build.sh
    FROM registry.ci.openshift.org/ocp/4.14:base
    RUN dnf install -y nmstate-libs && dnf clean all
    COPY --from=builder /go/src/github.com/openshift/agent-installer-utils/bin/agent-tui /usr/bin/agent-tui
    LABEL io.openshift.release.operator=true
